/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

import application.services.AuthorApplicationService;
import application.services.BookApplicationService;
import application.services.UserApplicationService;
import domain.repositories.AuthorRepository;
import domain.repositories.BookRepository;
import domain.repositories.UserRepository;
import infraestructure.controllers.AuthorController;
import infraestructure.controllers.BookController;
import infraestructure.controllers.UserController;
import infraestructure.persistence.AuthorRepositoryImpl;
import infraestructure.persistence.BookRepositoryImpl;
import infraestructure.persistence.UserRepositoryImpl;

/**
 *
 * @author sergi
 */
public class PrincipalView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalView.class.getName());
    private final UserController userController;
    private final AuthorController authorController;
    private final BookController bookController;
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();

        UserRepository userRepo = new UserRepositoryImpl();
        AuthorRepository authorRepo = new AuthorRepositoryImpl();
        BookRepository bookRepo = new BookRepositoryImpl();

        UserApplicationService userService = new UserApplicationService(userRepo);
        AuthorApplicationService authorService = new AuthorApplicationService(authorRepo);
        BookApplicationService bookService = new BookApplicationService(bookRepo, authorRepo);

        this.userController = new UserController(userService);
        this.authorController = new AuthorController(authorService);
        this.bookController =  new BookController(bookService);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuUsers = new javax.swing.JMenu();
        itemSearchUser = new javax.swing.JMenuItem();
        itemAddUser = new javax.swing.JMenuItem();
        itemEditUser = new javax.swing.JMenuItem();
        itemDeleteUser = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemReportsUsers = new javax.swing.JMenu();
        itemReportUsersAll = new javax.swing.JMenuItem();
        menuBooks = new javax.swing.JMenu();
        itemSearchBook = new javax.swing.JMenuItem();
        itemAddBook = new javax.swing.JMenuItem();
        itemEditBook = new javax.swing.JMenuItem();
        itemDeleteBook = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemReportsBooks = new javax.swing.JMenu();
        itemReportBooksAll = new javax.swing.JMenuItem();
        menuAuthors = new javax.swing.JMenu();
        itemSearchAuthors = new javax.swing.JMenuItem();
        itemAddAuthors = new javax.swing.JMenuItem();
        itemEditAuthors = new javax.swing.JMenuItem();
        itemDeleteAuthors = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemReportsAuthors = new javax.swing.JMenu();
        itemReportAuthorsAll = new javax.swing.JMenuItem();
        menuLoans = new javax.swing.JMenu();
        itemSearchUser3 = new javax.swing.JMenuItem();
        itemAddLoan = new javax.swing.JMenuItem();
        itemEditLoan = new javax.swing.JMenuItem();
        itemDeleteLoan = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemReportsLoan = new javax.swing.JMenu();
        itemReportLoanAll = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuUsers.setText("Users");

        itemSearchUser.setText("Search User");
        itemSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemSearchUser);

        itemAddUser.setText("Add User");
        itemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemAddUser);

        itemEditUser.setText("Edit User");
        itemEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemEditUser);

        itemDeleteUser.setText("Delete User");
        itemDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleteUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemDeleteUser);
        menuUsers.add(jSeparator1);

        itemReportsUsers.setText("Reports ");
        itemReportsUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportsUsersActionPerformed(evt);
            }
        });

        itemReportUsersAll.setText("All");
        itemReportUsersAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportUsersAllActionPerformed(evt);
            }
        });
        itemReportsUsers.add(itemReportUsersAll);

        menuUsers.add(itemReportsUsers);

        menuBar.add(menuUsers);

        menuBooks.setText("Books");
        menuBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBooksActionPerformed(evt);
            }
        });

        itemSearchBook.setText("Search Book");
        itemSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchBookActionPerformed(evt);
            }
        });
        menuBooks.add(itemSearchBook);

        itemAddBook.setText("Add Book");
        itemAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddBookActionPerformed(evt);
            }
        });
        menuBooks.add(itemAddBook);

        itemEditBook.setText("Edit Book");
        menuBooks.add(itemEditBook);

        itemDeleteBook.setText("Delete Book");
        menuBooks.add(itemDeleteBook);
        menuBooks.add(jSeparator2);

        itemReportsBooks.setText("Reports ");

        itemReportBooksAll.setText("All");
        itemReportBooksAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportBooksAllActionPerformed(evt);
            }
        });
        itemReportsBooks.add(itemReportBooksAll);

        menuBooks.add(itemReportsBooks);

        menuBar.add(menuBooks);

        menuAuthors.setText("Authors");

        itemSearchAuthors.setText("Search Authors");
        menuAuthors.add(itemSearchAuthors);

        itemAddAuthors.setText("Add Authors");
        itemAddAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddAuthorsActionPerformed(evt);
            }
        });
        menuAuthors.add(itemAddAuthors);

        itemEditAuthors.setText("Edit Authors");
        itemEditAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditAuthorsActionPerformed(evt);
            }
        });
        menuAuthors.add(itemEditAuthors);

        itemDeleteAuthors.setText("Delete Authors");
        menuAuthors.add(itemDeleteAuthors);
        menuAuthors.add(jSeparator3);

        itemReportsAuthors.setText("Reports ");

        itemReportAuthorsAll.setText("All");
        itemReportAuthorsAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportAuthorsAllActionPerformed(evt);
            }
        });
        itemReportsAuthors.add(itemReportAuthorsAll);

        menuAuthors.add(itemReportsAuthors);

        menuBar.add(menuAuthors);

        menuLoans.setText("Loans");

        itemSearchUser3.setText("Search Loan");
        menuLoans.add(itemSearchUser3);

        itemAddLoan.setText("Add Loan");
        itemAddLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddLoanActionPerformed(evt);
            }
        });
        menuLoans.add(itemAddLoan);

        itemEditLoan.setText("Edit Loan");
        menuLoans.add(itemEditLoan);

        itemDeleteLoan.setText("Delete Loan");
        menuLoans.add(itemDeleteLoan);
        menuLoans.add(jSeparator4);

        itemReportsLoan.setText("Reports ");

        itemReportLoanAll.setText("All");
        itemReportLoanAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportLoanAllActionPerformed(evt);
            }
        });
        itemReportsLoan.add(itemReportLoanAll);

        menuLoans.add(itemReportsLoan);

        menuBar.add(menuLoans);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void itemAddUserActionPerformed(java.awt.event.ActionEvent evt) {
        ViewUsers view = new ViewUsers(this, true, userController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemReportUsersAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemAddBookActionPerformed(java.awt.event.ActionEvent evt) {
        ViewBooks view = new ViewBooks(this, true, bookController, authorController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemReportBooksAllActionPerformed(java.awt.event.ActionEvent evt) {
        ViewReportBooks view = new ViewReportBooks(this, true, bookController, authorController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemAddAuthorsActionPerformed(java.awt.event.ActionEvent evt) {
        ViewAuthors view = new ViewAuthors(this, true, authorController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemReportAuthorsAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemAddLoanActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemReportLoanAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemSearchBookActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemEditAuthorsActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void itemSearchUserActionPerformed(java.awt.event.ActionEvent evt) {
        ViewUsers view = new ViewUsers(this, true, userController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemEditUserActionPerformed(java.awt.event.ActionEvent evt) {
        ViewUsers view = new ViewUsers(this, true, userController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void itemDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {
        ViewUsers view = new ViewUsers(this, true, userController);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }

    private void menuBooksActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void itemReportsUsersActionPerformed(java.awt.event.ActionEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem itemAddAuthors;
    private javax.swing.JMenuItem itemAddBook;
    private javax.swing.JMenuItem itemAddLoan;
    private javax.swing.JMenuItem itemAddUser;
    private javax.swing.JMenuItem itemDeleteAuthors;
    private javax.swing.JMenuItem itemDeleteBook;
    private javax.swing.JMenuItem itemDeleteLoan;
    private javax.swing.JMenuItem itemDeleteUser;
    private javax.swing.JMenuItem itemEditAuthors;
    private javax.swing.JMenuItem itemEditBook;
    private javax.swing.JMenuItem itemEditLoan;
    private javax.swing.JMenuItem itemEditUser;
    private javax.swing.JMenuItem itemReportAuthorsAll;
    private javax.swing.JMenuItem itemReportBooksAll;
    private javax.swing.JMenuItem itemReportLoanAll;
    private javax.swing.JMenuItem itemReportUsersAll;
    private javax.swing.JMenu itemReportsAuthors;
    private javax.swing.JMenu itemReportsBooks;
    private javax.swing.JMenu itemReportsLoan;
    private javax.swing.JMenu itemReportsUsers;
    private javax.swing.JMenuItem itemSearchAuthors;
    private javax.swing.JMenuItem itemSearchBook;
    private javax.swing.JMenuItem itemSearchUser;
    private javax.swing.JMenuItem itemSearchUser3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu menuAuthors;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBooks;
    private javax.swing.JMenu menuLoans;
    private javax.swing.JMenu menuUsers;
    // End of variables declaration
}
